http:
    # port for app to listen on
    port: 8080
logging:
    console:
        # console log level
        level: info
    file:
        # file log location, remove if only logging to console, also has level
        filename: /var/log/node-munin-comparison.log
# munin data files location
datafiles: /var/lib/munin